### ISSUE TITLE
Some time the render things don't display

### ISSUE THREAD

**Issue by ArionTT** [daktronics/cef-mixer#11] opened 2018-04-19 01:45 UTC
Hi, I add some D3D11 Rendering in [here](https://github.com/daktronics/cef-mixer/blob/8d4bcc7af69436f196ad7edc3611a1fb10ff68a2/src/composition.cpp#L208), I replace the create_image_layer call with create_d3drender_layer that I wrote. In the end, I render a D3D box into a D3D11Texture and render the texture into Quad.

But there is a problem. When I build with Debug ( I link the release version cef lib in debug mode ), some time the application don't render my box, some time my box show. The times is very random. Is it normal?

After that I try to build Release version, and the box render ,the HTML web page disappear...
I don't know what's happened...

**Comment by wesselsga** [comment] 2018-04-19 02:34
Can you share the code for your custom layer created with `create_d3drender_layer`?

**Comment by ArionTT** [comment] 2018-04-19 02:43
Did you mean I paste the code in the reply? The code is a little long.
Or did you mean to uploading my code file?
I don't know how to share my code, I m not very familiar to Git.

**Comment by wesselsga** [comment] 2018-04-19 02:49
You should be able to just attach the code file in a comment in this issue.  Drag-and-drop the file in the edit box.

**Comment by ArionTT** [comment] 2018-04-19 03:01
[d3d_layer.txt](https://github.com/daktronics/cef-mixer/files/1926482/d3d_layer.txt)
（P.S. the file format github.com support don't contain the .cpp file, so I change it to a TXT file）

This is my render result screenshot :
 
![qq 20180418112705](https://user-images.githubusercontent.com/21036443/38969039-d0f09aec-43c0-11e8-9991-7a42d9778ee2.png)

**Comment by wesselsga** [comment] 2018-04-19 03:05
TXT is fine, but I'll probably need the cube.fx file as well

**Comment by ArionTT** [comment] 2018-04-19 03:08
[cube.txt](https://github.com/daktronics/cef-mixer/files/1926502/cube.txt)
This fx file is very simple to translate the cube vertex to projection space and output a color.

**Comment by wesselsga** [comment] 2018-04-19 04:11
I was able to piece it together.  In DEBUG, there is a flood of D3D11 warnings (I know they should be harmless) - but I got rid of them anyway:

```c
D3D11 WARNING: ID3D11DeviceContext::PSSetShaderResources: Resource being set to PS shader resource slot 0 is still bound on output! Forcing to NULL. [ STATE_SETTING WARNING #7: DEVICE_PSSETSHADERRESOURCES_HAZARD]
```

I moved the following line:

```c
pContext->PSSetShaderResources(0, 1, &pShaderResourceView);
```
So that it is the last statement in the PreRender() method.

As far as the HTML not showing up ... its because your 3D scene is covering it up.  The HTML is playing on a layer behind your custom layer.

I changed your clear color to transparent:

```c
//float clearColor[] = { 0.8f,0.2f,0.0f,1.0f };
float clearColor[] = { 0.0f,0.0f,0.0f,0.0f };
pContext->ClearRenderTargetView(pRenderTargetView, clearColor);
```

And everything showed up fine.  I haven't seen any intermittent issues here?

![custom_cube](https://user-images.githubusercontent.com/2717038/38970883-afc2757e-435d-11e8-9865-a80a57602121.png)

**Comment by ArionTT** [comment] 2018-04-19 04:49
Thanks, I change the ClearColor to transparent, the cube display well.

But There is a difference between the Debug result and Release result. 

The Debug screenshot:
![20180419123433](https://user-images.githubusercontent.com/21036443/38971533-41219d22-43ce-11e8-932b-e8206d7cedc3.png)

The Release screenshot:
![20180419123512](https://user-images.githubusercontent.com/21036443/38971548-4d3c01a6-43ce-11e8-96e5-ad59bb6f6ac7.png)

The last HTML page disappear....

The Code like this:
`		auto const ui_file = locate_media("resource/UI.html");`
`		if (ui_file)`
`		{`
`			auto const ui_url = to_file_url(*ui_file);`
`			if (!ui_url.empty())`
`			{`
`				builder << "    { \"type\":\"web\"," << std::endl`
`				<< "      \"src\":\"" << ui_url << "\"," << std::endl`
`					<< "      \"left\":0.3," << std::endl`
`					<< "      \"top\":0.3," << std::endl`
`					<< "      \"width\":0.4," << std::endl`
`					<< "      \"height\":0.4" << std::endl`
`					<< "    }," << std::endl;`
`			}`
`		}`

I just copy the states bar code.The UI.html[UI.txt](https://github.com/daktronics/cef-mixer/files/1926636/UI.txt)
This web layer is the last layer.

Is the problem caused by DEBUG version cef lib file?


P.S.
There was another problem in my screenshot. I switch project to Debug and run the application, the result sometimes like this:
![qq 20180419123343](https://user-images.githubusercontent.com/21036443/38971762-3f094a70-43cf-11e8-96d8-37aeb73ecd0c.png)
The Cube disappeared. Sometime, it run normally.

And I switch to Release and run application five times, it is all right.

**Comment by wesselsga** [comment] 2018-04-19 12:41
The cube not showing up is a little puzzling.  If you're using my sample binary distribution of CEF, make sure you're on the latest build.  I can tell from your Window title that we're using different versions.

Easy way to run DEBUG versions of cefmixer:

1) Download latest sample distribution and extract
2) Copy the Release folder in the distribution and re-name it to Debug
3) Set **CEF_ROOT** to the path of your CEF distributation and run **gen_vs2017.bat**
4) Open cefmixer in Visual Studio and build Debug

**Comment by wesselsga** [comment] 2018-04-19 13:28
Also, `cefmixer` is using single-process for DEBUG builds (easier to step through Chromium code)

```c
#if defined(NDEBUG)
	settings.single_process = false;
#else
	// ~RenderProcessHostImpl() complains about DCHECK(is_self_deleted_)
	// when we run single process mode ... I haven't figured out how to resolve yet
	settings.single_process = true;
#endif
```

I would test on your end with `settings.single_process = false;` **always ** set to **false**

**Comment by wesselsga** [comment] 2018-05-22 16:51
Closing issue - I don't think the issue is with the cef-mixer project or cef pull request.

**Closed by wesselsga** 2018-05-22 16:51 UTC
